### ISSUE TITLE
Prepare for Internationalization - Language Changer + Index Page Alternative Copy

### ISSUE THREAD

**Issue by zachdt** [leaseOTB/website#3]
The leaseOTB website goes international! 

We need a method to change language site-wide, and serve alternative copy based on selected language.  This issue covers only the index/landing page, no other components.  Right now we are looking to use English and Spanish as our two languages.

https://www.gatsbyjs.org/packages/gatsby-plugin-intl/?=internationaliz

**Comment by Josh1794** [comment]
- [ ] Convert existing text to pull from JSON file

- [ ] Add localization support

- [ ] Add translation JSON files
